#ifndef FACE_API_H
#define FACE_API_H

#include "../hss_core/hss_core.h"
#include <stdint.h>

// ==========================================
// Face Recognition Configuration
// ==========================================
// 阈值 Tau (0.0 - 1.0)
// 我们将其表示为分数 (NUM/DEN) 以进行整数运算
// 增加阈值到 0.9 以提高区分度 (Dlib 向量需要更高的阈值)
#define FACE_TAU_NUM 9
#define FACE_TAU_DEN 10

// 安全边界检查：最大合法内积的绝对值
// 假设特征值在 [-2.0, 2.0] 之间，量化因子 65536
// 最大内积约等于 128 * (2 * 65536)^2 ≈ 2.2 * 10^12
// 我们设定一个稍大但远小于 P(10^18) 的阈值，如 10^13
#define MAX_EXPECTED_IP 10000000000000LL

// ==========================================
// Protocol Data Structures
// ==========================================

// --- Phase 1: Enrollment ---

// Cref (Reference Ciphertext)
// Stored on the Server. Generated by the User during enrollment.
typedef struct {
    HSS_PubB pub_vec;
    uint64_t ref_norm_sq; // Plaintext squared norm of the reference template
} Auth_Cref;

// Witness (Secret State)
// Kept securely on the User's device.
typedef struct {
    HSS_StateB state_vec;
} Auth_Witness;


// --- Phase 2: Authentication ---

// Cprb (Probe Ciphertext / Challenge)
// Sent from Server to User. Generated using the live probe template.
typedef struct {
    HSS_PubA pub_vec;
} Auth_Cprb;

// Response (User's Decryption Share)
// Sent from User back to Server.
typedef struct {
    hss_int_t z_U; // User's computed share (z_B in underlying HSS)
} Auth_Response;

// Server Verification State
// Kept locally by the Server while waiting for the User's response.
typedef struct {
    HSS_StateA state_vec;
    hss_int_t z_S; // Server's computed share (z_A in underlying HSS)
    uint64_t ref_norm_sq;  // Copied from Cref
    uint64_t prb_norm_sq;  // Computed from probe template
} Auth_ServerVerifyState;

// ==========================================
// API Functions
// ==========================================

// Setup CRS
void face_auth_setup(HSS_CRS *crs);

// Phase 1: Enrollment
// User computes Cref (to send to Server) and Witness (to keep local)
void face_auth_enroll(const HSS_CRS *crs, 
                      const float *reference_template, 
                      Auth_Cref *c_ref_out,
                      Auth_Witness *witness_out);

// Phase 2 - Step 1: Challenge (Server-side)
// Server uses live probe template and stored Cref to generate a Challenge (Cprb)
void face_auth_challenge(const HSS_CRS *crs, 
                         const float *probe_template,
                         const Auth_Cref *c_ref,
                         Auth_Cprb *c_prb_out,
                         Auth_ServerVerifyState *verify_state_out);

// Phase 2 - Step 2: Response (User-side)
// User uses their secret Witness to answer the Server's Challenge
void face_auth_respond(const HSS_CRS *crs,
                       const Auth_Cprb *c_prb,
                       const Auth_Witness *witness,
                       Auth_Response *response_out);

// Phase 2 - Step 3: Verify (Server-side)
// Server reconstructs the similarity score and makes the final decision
int face_auth_verify(const Auth_Response *response,
                     const Auth_ServerVerifyState *verify_state);

#endif
